name: Deploy Workflow

on:
  push:
    branches:
      - main # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Deploy SSH keys
        env:
          MITTWALD_SSH_PRIVATE_KEY: ${{ secrets.MITTWALD_SSH_PRIVATE_KEY }}
          MITTWALD_SSH_PUBLIC_KEY: ${{ secrets.MITTWALD_SSH_PUBLIC_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${MITTWALD_SSH_PRIVATE_KEY}" > ~/.ssh/halici
          echo "${MITTWALD_SSH_PUBLIC_KEY}" > ~/.ssh/halici.pub
          chmod 600 ~/.ssh/halici
          chmod 644 ~/.ssh/halici.pub

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ssh.gestringen.project.host >> ~/.ssh/known_hosts

      - name: Configure SSH
        run: |
          echo "Host ssh.gestringen.project.host" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/halici valera19079@gmail.com@e2d57b1f-f959-49d9-a3ed-e9f1e7d06604@ssh.gestringen.project.host "echo 'SSH connection successful'"
        # Replace <your-username> with the correct username

      - name: Run deployer
        run: |
          ./vendor/bin/dep deploy \
            -o mittwald_app_id=${{ secrets.MITTWALD_APP_ID }} \
            -o mittwald_ssh_public_key_file=~/.ssh/halici.pub \
            -o mittwald_ssh_private_key_file=~/.ssh/halici
        env:
          MITTWALD_API_TOKEN: ${{ secrets.MITTWALD_API_TOKEN }}
