name: Deploy Workflow

on:
  push:
    branches:
      - main # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Deploy SSH keys
        env:
          MITTWALD_SSH_PRIVATE_KEY: ${{ secrets.MITTWALD_SSH_PRIVATE_KEY }}
          MITTWALD_SSH_PUBLIC_KEY: ${{ secrets.MITTWALD_SSH_PUBLIC_KEY }}
        run: |
          mkdir -p .mw-deploy
          echo "${MITTWALD_SSH_PRIVATE_KEY}" > .mw-deploy/halici
          echo "${MITTWALD_SSH_PUBLIC_KEY}" > .mw-deploy/halici.pub
          chmod 600 .mw-deploy/halici*

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ssh.gestringen.project.host > ~/.ssh/known_hosts

      - name: Run deployer
        run: |
          ./vendor/bin/dep deploy \
            -o mittwald_app_id=${{ secrets.MITTWALD_APP_ID }} \
            -o mittwald_ssh_public_key_file=.mw-deploy/halici.pub \
            -o mittwald_ssh_private_key_file=.mw-deploy/halici
        env:
          MITTWALD_API_TOKEN: ${{ secrets.MITTWALD_API_TOKEN }}
